#production
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 123456

#development
development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: kickrstack_development
  host: localhost
  pool: 5
  username: postgres
  password: 123456
